version: 0.2

phases:
  pre_build:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm cache clean --force  
      - npm run generate-env
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build